DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS BOOKS_AUTHORS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;

CREATE TABLE GENRES
(
	GENRE_ID INT auto_increment PRIMARY KEY, 
	NAME VARCHAR(255) NOT NULL,
	UNIQUE KEY GENRE_NAME_UNIQUE (NAME)
);

CREATE TABLE BOOKS
(
	BOOK_ID INT auto_increment PRIMARY KEY, 
	NAME VARCHAR(255) NOT NULL, 
	GENRE_ID INT NOT NULL,
	foreign key(GENRE_ID) references GENRES(GENRE_ID)
);

CREATE TABLE AUTHORS
(
	AUTHOR_ID INT auto_increment PRIMARY KEY, 
	SURNAME VARCHAR(255) NOT NULL, 
	FIRSTNAME VARCHAR(255) NOT NULL, 
	MIDDLENAME VARCHAR(255)
);

CREATE TABLE BOOKS_AUTHORS
(
	BOOK_ID INT NOT NULL, 
	AUTHOR_ID INT NOT NULL,
	foreign key(BOOK_ID) references BOOKS(BOOK_ID),
	foreign key(AUTHOR_ID) references AUTHORS(AUTHOR_ID),
	PRIMARY KEY(BOOK_ID, AUTHOR_ID)
);

CREATE TABLE COMMENTS
(
	COMMENT_ID INT NOT NULL,
    BOOK_ID INT NOT NULL,
    COMMENTATOR VARCHAR(255) DEFAULT 'Anonym',
    CONTENT VARCHAR(255),
	SCORE SMALLINT NOT NULL,
	foreign key(COMMENTED_BOOK_ID) references BOOKS(BOOK_ID),
	PRIMARY KEY(COMMENT_ID)
);